.gitignore, _tasks/star.ts, deno.jsonc
`deno task star` on fresh repos was causing a failure, since we no longer require a bootstrap step (which previously created a now-non-existent `target` dir). Caused a dir-not-found err.
=> chore: fix star task

deno.jsonc
=> chore: add task test-update

_tasks/download_frame_metadata.ts, examples/balance.ts, examples/events.ts, examples/first_ten_keys.ts, examples/metadata.ts, examples/rpc/call.ts, examples/rpc/subscription.ts, examples/transfer.ts, rpc/Base.ts, rpc/auto.ts, rpc/messages.ts, rpc/methods.ts, rpc/mod.ts, rpc/smoldot.ts, rpc/ws.ts
This PR changes the RPC interface.
We must now create a beacon, the type of which is encoded with supported methods.
The following is a beacon that only supports the `state_getMetadata` method.
```ts
import * as rpc from "capi/rpc";
const beacon = rpc.beacon<"state_getMetadata">([URL]);
```
We can allow all methods by simply omitting the type arg.
```ts
const beacon = rpc.beacon([URL]); // supports all methods
```
Now we can create the client:
```ts
const client = await rpc.client(beacon);
```
We'll get a type error if we attempt to utilize methods that are NOT encoded in the beacon as accessible.
```ts
// Allow only the `state_getStorage` method
const client = await rpc.client(rpc.beacon<"state_getStorage">(polkadotBeacon));
// Ensure that the client was successfully opened …
```
=> feat: encode narrow RPC methods in beacon, propagate to messages

_deps/smoldot.ts, _tasks/dnt.ts
This version of smoldot contains adds `{type: "module"}` to the Web Worker in order to be supported for deno
=> chore: bump smoldot-light to version 0.6.20

_deps/scale.ts, core/Block.ts, examples/block.ts, frame_metadata/Codec.ts, frame_metadata/Extrinsic.ts, runtime/read.ts
```ts
import { polkadot } from "capi/known";
const result = await polkadot.block().read();
```
`result.block.extrinsics` may look––for example––as follows:
```ts
[
{
protocolVersion: 4,
signature: undefined,
palletName: "Timestamp",
methodName: "set",
args: { now: 1656730165771 }
},
{
protocolVersion: 4,
signature: undefined,
palletName: "ParaInherent",
methodName: "enter",
args: {
data: {
bitfields: [Array],
backed_candidates: [Array],
disputes: [Array],
parent_header: [Object]
}
}
}
]
```
=> feat: decoding extrinsics within blocks

effect/atoms/Codec.ts, effect/atoms/Decoded.ts, effect/atoms/DeriveCodec.ts, effect/atoms/ExtrinsicCodec.ts, effect/atoms/KeyCodec.ts, effect/atoms/Metadata.ts, effect/atoms/RpcCall.ts, effect/atoms/RpcClient.ts, effect/atoms/Select.ts, effect/atoms/StorageKey.ts, effect/atoms/Wrap.ts, effect/atoms/mod.ts, effect/examples/block.ts, effect/examples/first_ten_keys.ts, effect/run.ts, effect/std/block/read.ts, effect/std/keyPage/read.ts, effect/std/keys/read.ts, effect/sys/Atom.ts, effect/sys/Run.ts, effect/sys/mod.ts, examples/first_ten_keys.ts, frame_metadata/Extrinsic.ts
Let's say you have the following effect:
```ts
const decoded = sys.atom(
"Anonymous",
[$key, keysEncoded],
(keyCodec, keysEncoded) => {
return keysEncoded.map((keyEncoded) => {
return keyCodec.decode(U.hex.decode(keyEncoded));
});
},
);
```
You can refactor the impl to a function function...
```diff
const decoded = sys.atom(
"Anonymous",
[$key, keysEncoded],
- (keyCodec, keysEncoded) => {
+ function(keyCodec, keysEncoded) {
return keysEncoded.map((keyEncoded) => {
return keyCodec.decode(U.hex.decode(keyEncoded));
});
},
);
```
... which gives access to the executor via `this`:
```diff
const decoded = sys.atom(
"Anonymous",
[$key, keysEncoded],
function(keyCodec, keysEncoded) {
+   this.run(anotherEffect); // would likely––in practice––await and use the result
return …
```
=> feat: effects can spawn new runs, key page and block reads

effect/examples/derived.ts, effect/sys/Atom.ts, effect/sys/Run.ts, effect/sys/key.ts
For example, let's read the list of parachain ids and then use these ids to read their heads.
```ts
// TODO: expose these with greater simplicity
import { polkadot } from "capi/known/mod.ts";
import { run } from "./capi.ts";
import { readEntry } from "../std/entry/read.ts";
import { all, into } from "../sys/mod.ts";
// 1. Read the Ids
const parachainIds = readEntry(polkadot, "Paras", "Parachains", []);
// 2. `Into` from `parachainIds` into a new effect
const parachainHeads = into([parachainIds], ({ value }) => {
// Use each id in the `value` list to create a new read effect
const atoms = value.map((id) => {
return readEntry(polkadot, "Paras", "Heads", [id]);
});
// Can be thought of in a similar vein to `Promise.all`
return all(...atoms);
});
// 3. Run it all at once!
const result = await …
```
=> feat: utils for derived queries

effect/sys/Atom.ts, examples/those_of_subxt/read_era_rewards.ts
Enables the following, for instance:
```ts
const idx = C
.readEntry(C.polkadot, "Staking", "ActiveEra", [])
.select("value")
.select("index");
```
Cleaner than...
```ts
const idx = C.select(
C.select(
C.readEntry(C.polkadot, "Staking", "ActiveEra", []),
"value"
),
"index",
);
```
=> feat: add select to atom

.github/dependabot.yml, .github/workflows/configure.yml, .github/workflows/fmt.yml, .github/workflows/release.yml, .github/workflows/spellcheck.yml, .github/workflows/test.yml, .github/workflows/udd.yml
In order to improve our security posture with GitHub Actions usage. I've made a version pinning ether to commit hash or to specific version.
Additionally added `dependabot` to track GHA version changes.
Related issues and policy:
https://github.com/paritytech/ci_cd/issues/114
https://github.com/paritytech/ci_cd/issues/464
https://github.com/paritytech/ci_cd/wiki/Policies-and-regulations:-GitHub-Actions-usage-policies
=> Pin GHA versions and add dependabot

_tasks/.gitignore, _tasks/run_browser.ts, deno.jsonc, test-util/config.ts
Allows testing the various examples in the browser via e.g.
```sh
deno task run:browser examples/transfer.ts
```
The task file is a bit hacked together, but as it's an internal util, I think this is fine.
=> chore: add `run:browser` task

effect/atoms/StorageKey.ts, frame_metadata/Key.test.ts, frame_metadata/Key.ts
Fixes #193.
This changes `$storageKey` to deal with keys in a tuple form (`[]`/`[A]`/`[A,B,...]`), rather than a collapsed form (`null`/`A`/`[A,B,...]`). The collapsed form was never being used in user code, so this just resulted in unnecessary extra work.
It also fixes the bug behavior of `$storageKey` for multi-part keys described in <https://github.com/paritytech/capi/issues/193#issuecomment-1231675617>.
=> fix: storage key handling

.vscode/launch.json
Configure VSCode `launch.json` for Deno scripts debugging
- add a breakpoint to a `*.ts` file, run the `Debug current file` and validate that the VSCode debugger stops at the breakpoint
- add a breakpoint to a `*.test.ts` file, run the `Debug current test file` and validate that the VSCode debugger stops at the breakpoint
=> chore: add VSCode debugging configuration

.github/workflows/test.yml, effect/extrinsic.test.ts, effect/sys/run.ts, test-util/config.ts
Add a simple extrinsic integration test that depends on the `polkadot` binary.
The `polkadot` binary is copied from the polkadot docker image.
- validate that the test workflow action has run the `effect/extrinsic.test.ts` test
- check the test workflow logs to validate that the `polkadot` node was started during the test
=> feat: add extrinsic integration test

effect/atoms/$Extrinsic.ts, effect/std/submitAndWatchExtrinsic.ts, examples/polkadot_signer.ts, frame_metadata/Extrinsic.ts, known/configs.ts, util/hex.ts
Should unblock @karl-kallavus
```ts
deno task run examples/polkadot_signer.ts
```
I've also tested this on the web
=> feat: polkadot signer

_tasks/dnt.ts, codegen/codecVisitor.ts, codegen/genMetadata.ts, codegen/typeVisitor.ts, codegen/utils.ts, deps/scale.ts, deps/std/testing/asserts.ts, deps/std/testing/snapshot.ts, effect/atoms/Codec.ts, frame_metadata/Codec.test.ts, frame_metadata/Codec.ts, frame_metadata/Extrinsic.ts, frame_metadata/Metadata.test.ts, frame_metadata/Metadata.ts, frame_metadata/TyVisitor.ts, frame_metadata/scale_info.ts, hashers/mod.test.ts
Resolves #284 
This changes the structure of the metadata to be recursive; where before compound types would reference other types via indices, they now reference the type object itself directly. This uses the new context api in scale v0.6.0 to decode directly into this structure, without any need for post-processing.
This eliminates almost all cases where one would need to index into the `metadata.tys` array, cleaning up the code significantly.
The only part that became more complicated was `Metadata.test.ts`. Though Deno's snapshot serializer *does* support circular references, it only uses references to parent objects in the circularity. This meant that it produced a – though finite – pathologically large string, as each type was written in expanded form potentially hundreds of times. …
=> feat: recursive metadata structure

rpc/providers/proxy.test.ts
The RPC test was failing. This is likely due to the fact that it made use of a remote RPC node, which may rate limit / is sometimes unavailable. This PR changes the test to utilize a local node instead.
=> chore: fix failing RPC test

.github/actions/setup-polkadot/action.yml, .github/workflows/example.yml, .github/workflows/spawn_examples.yml, effect/std/watchEntry.ts, examples/ticker.ts, words.txt
Resolves #299 
Run examples in parallel using reusable workflows.
The caller workflow `spawn_examples.yml` generates the list of example paths and calls the `example.yml` reusable workflow.
The `example.yml` workflow uses a marix strategy to create a job for each example file.
Also, this PR adds a `setup-polkadot` composite action that caches and downloads the polkadot binary.
I'd like to get some feedback on the composite action before integrating it in other workflows
=> feat: add example GH action

.github/workflows/spawn_examples.yml
Filter `*.ts` files in `spawn_example` workflow
=> fix: filter .ts files for spawn_examples GH action

.github/workflows/release.yml, .github/workflows/udd.yml
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#environment-files
=> chore: update ci to use env files instead of `set-output`

.github/actions/setup-fd-find/action.yml, .github/workflows/spawn_examples.yml, examples/.ignore
Switch `find` with `fd-find` to support `.ignore` files inside `./examples`
https://github.com/sharkdp/fd#installation
=> feat: add .ignore support for spawn_example workflow

effect/EntryRead.ts, effect/EntryWatch.ts, effect/Extrinsic.ts, effect/KeyPageRead.ts, effect/Metadata.ts, effect/extrinsic.test.ts, effect/mod.ts, examples/polkadot_js_signer.ts, examples/transfer.ts, rpc/Base.ts, rpc/messages.ts
Now that various effects utilize `Z.Name`, we can attach methods to simplify their APIs.
Metadata:
```ts
const entryMetadata = new C.Metadata(T.polkadot)
.pallet("Balances")
.entry("Account");
```
Extrinsics:
```ts
const root = new C.Extrinsic(T.westend, {
sender: {
type: "Id",
value: T.alice.publicKey,
},
palletName: "Balances",
methodName: "transfer",
args: {
value: 12345n,
dest: {
type: "Id",
value: T.bob.publicKey,
},
},
})
.signed((message) => ({
type: "Sr25519",
value: T.alice.sign(message),
}))
.watch((stop) => {
return (event) => {
// ...
};
});
```
^ this paves the way for the non-watched counterpart.
=> chore: cleanup to metadata and extrinsic effect apis

frame_metadata/Codec.ts
=> fix: derive compact codec for single-field structs

codegen.ts, codegen/Files.ts, codegen/codecVisitor.ts, codegen/mod.ts, codegen/typeVisitor.ts, codegen/utils.ts, deno.jsonc, test_util/codegen.ts, words.txt
Resolved #258
This PR includes a variety of tweaks to the CLI:
- specify target chain via SCALE or chainspec file paths or WebSocket URL.
- choose the Capi import specifier of codegened output (denoland/x is the default). This enables us to override to a local version or the NPM name.
Usage is slightly different.
```
deno run -A -r https://deno.land/x/capi/codegen.ts \
--src=wss://rpc.polkadot.io \
--out=polkadot \
--import=capi
```
In the context of this repo, we could run the following:
```
deno task run codegen.ts \
--src=wss://rpc.polkadot.io \
--out=polkadot \
--import=mod.ts
```
Given that we specify `mod.ts` as the Capi import specifier, the files generated into the `polkadot` dir will import capi via `../mod.ts`.
=> chore: reworking CLI + import specifiers

codegen.ts, config/mod.ts, effects/const.ts, effects/core/decoded.ts, effects/entryRead.ts, effects/extrinsic.ts, effects/metadata.ts, effects/mod.ts, frame_metadata/Metadata.ts, known/configs.ts, test_util/config.ts
An effect which decodes constants within the metadata, such as `System`'s `SS58Prefix`, which we now use instead of hard-coding.
=> feat: `const` effect for decoding consts in the metadata

effects/common.ts, effects/extrinsic.ts, effects/metadata.ts, effects/rpcSubscription.ts, frame_metadata/Codec.ts, frame_metadata/Key.ts, frame_metadata/Metadata.ts, hashers/mod.ts, rpc/common.ts, rpc/providers/proxy.ts, rpc/providers/smoldot.ts, ss58/mod.test.ts, ss58/mod.ts, util/error.ts
- Return instead of throw from Ss58 transcoders
- Create new error ctors without a bespoke util
=> chore: error cleanup

effects/extrinsic.ts
- Can grab relevant versions from constants instead
- Misc. cleanup
=> chore: get rid of extra RPC call in extrinsic effect

examples/batch.ts
Simple batch call example. Checks 4 users' free balances before and after the batch call.
=> chore: add batch example

_tasks/dnt.ts, deps/scale.ts
The NPM package name also changed to `scale-codec`
=> chore: update to scale v0.8.2

_tasks/dnt.ts, deps/scale.ts, effects/extrinsic.ts, frame_metadata/Era.ts, frame_metadata/Extrinsic.ts, frame_metadata/Key.ts, frame_metadata/scale_info.ts
Will swap out the import specifier pending paritytech/scale-ts#118.
**EDIT**: swapped it out
=> feat: runtime validation

deps/smoldot.ts, rpc/client.ts, rpc/provider/errors.ts, rpc/provider/proxy.ts, rpc/provider/smoldot.test.ts, rpc/provider/smoldot.ts
Resolves #376
Improve Smoldot integration for relay chains by
- capturing Smoldot errors
- mapping specific `.send` requests to specific `.send` calls
Smoldot parachain integration will be tacked in an upcoming PR
=> feat: improve smoldot integration

effects/extrinsic.ts, examples/fee_estimate.ts, rpc/known/payment.ts
Resolves #337
Add `.feeEstimate` to the extrinsic effect.
Also updates `Weight` v2 type to `RuntimeDispatchInfo`.
=> feat: add tx fee estimate

deno.jsonc, examples/multisig_transfer.ts
Use `extrinsic.feeEstimation` to compute multisig `max_weight`
=> feat: compute max_weight for multisig example

codegen/server/server.ts
Fixes the `C.rpc.Client` setup
=> fix: codegen rpc.Client setup

_tasks/dnt.ts, deps/capi_crypto_wrappers.ts
Resolves #434 
- For deno & fresh, it inlines the wasm blob in the JS (url fetch wasn't working with fresh) but loads it asynchronously to support browsers' limit on synchronous wasm instantiation
- For node, it inlines the wasm blob in the JS and loads it synchronously as node doesn't support TLA
=> fix: update `capi_crypto_wrappers` for browser support

codegen/server/server.ts
Fixes e.g. https://capi.dev/@ref:main
=> fix: stop redirecting to `/@sha:abc123undefined`

Readme.md
broken link... any other docs links need a check?
=> docs: fix broken link

docs/Types.md, frame_metadata/Metadata.ts
I see prettier is used in the  .vscode setting elsewhere, use it in md too.
[Metadata.test.ts.snap](https://github.com/paritytech/capi/pull/457/files#diff-e9670ee5a561952b762271c45942a6d95ea4e4ccdc6f0b2b4e1964b3aa683a33) -- Found more links issues, but I think this is a generated file, so actually the runtime has the wrong links embedded in them? :grimacing: 
If so, can put in redirects on docs for these
=> docs: update links

.github/workflows/check_secrets.yml, .github/workflows/deno_deploy.yml, .github/workflows/fmt.yml, .github/workflows/spawn_examples.yml, .github/workflows/spellcheck.yml, .github/workflows/test.yml, rpc/client.ts
Resolves #469
- Fixes the compiler error and updates the `id` check of `IngressMessage` to just check if the `id` is undefined or not. It can never be a number base on the type definition: https://github.com/paritytech/capi/blob/fix/test-suite/rpc/messages.ts#L9. 
- Adds CI to PR builds -- i.e. in the case of a forked repo submitting a PR.
- Fixes one of the workflows pointing from `master` to `main`.
=> fix: ci & issue re deno upgrade

.devcontainer/devcontainer.json, Dockerfile
Resolves #463
Add dev as a new build stage in docker and install `zsh` in that stage; dev container file updated to point to `dev` stage. This ensures `zsh` is installed in dev builds and not production builds.
=> feat: add zsh to dev container

.editorconfig, .github/workflows/test.yml, codegen/server/cache.ts, codegen/server/deploy.ts, codegen/server/local.ts, codegen/server/server.ts, codegen/typeVisitor.ts, deno.jsonc, dprint.json, effects/blockWatch.ts, examples/batch.ts, examples/multisig_transfer.ts, examples/polkadot_js_signer.ts, examples/transfer.ts, rpc/client.ts, test_util/extrinsic.ts, util/memo.ts, words.txt
- Re-enable unnecessary `async` lint
- Clean up `deno.jsonc`
- Update dprint plugins
- Update editorconfig to align with dprint config
=> chore: misc config cleanup

.devcontainer/devcontainer.json, .github/workflows/dev-container.yml, Dockerfile
Resolves #465
Fix dev container build not working and add gh action to ensure the build always passes.
=> chore: add gh action for dev container builds

.github/workflows/dev-container.yml, .github/workflows/fmt.yml, .github/workflows/spawn_examples.yml, .github/workflows/spellcheck.yml, .github/workflows/test.yml
=> fix: duplicate workflows in push and pull_request

.gitpod.yml, Dockerfile, words.txt
Add `zombienet-linux` and `polkadot-parachain` binaries to the docker image
**How to test?**
- https://gitpod.io/#https://github.com/paritytech/capi/tree/feat/zombienet-devcontainer
- open the terminal and run `deno task run examples/smart_contract.ts`
Note: using docker in M1 Macs it doesn't work and it seems to be related to `qemu-x86_64` CPU emulation.
=> feat: add zombienet and polkadot-parachain to devcontainer

_tasks/dnt.ts, codegen/genCodecs.ts, deps/scale.ts, effects/contracts/events.ts, frame_metadata/Metadata.ts, ink_metadata/known.ts, primitives/MultiAddress.ts, primitives/MultiSignature.ts, scale_info/Codec.ts, scale_info/Ty.ts, scale_info/overrides/Era.ts, util/hashers.test.ts
Resolves #497.
One minor downside to this change is that the types can no longer "catch" the optional fields. i.e. if the field is optional and we don't put it in the codec then it wont be caught by the compiler.
=> chore: update scale dependency to 0.10.0

.devcontainer/devcontainer.json, Dockerfile
=> chore: update dev container to use different base

effects/extrinsic.ts, util/error.ts, util/ss58.test.ts, util/ss58.ts
Previously, errors were returned from this utility. This is not a common pattern (even though we do so in Zones/soon Rune). Figured it should be split out of the raw ss58 utils.
=> chore: misc ss58 cleanup

examples/watch.ts, rune/Rune.test.ts, rune/Rune.ts, rune/rune.md
Resolves #579
The name `iter` is more fitting than `watch` bc this method will also be used for getting iterators from non-subscription meta runes (for instance, key page iteration (#567)).
=> chore: rename `rune.watch` to `rune.iter`

fluent/ExtrinsicStatusRune.ts, rune/ValueRune.ts
- make the `dbg` method on `ValueRune` accept Runes as prefixs
- make the `logStatus` of `extrinsicStatusRune` accept Runes as prefixes
- add a `log` method on `ValueRune` (currently does same thing as `dbg`, which will be reworked upon resolution of #517)
=> chore: log util cleanup

rune/Rune.ts
A tagged template fn for interpolating Runes in a string
```ts
const name = Rune.constant("Capi")
const message = Rune.str`Hello ${name}!`
```
=> feat: `Rune.str`

providers/frame/FrameProxyProvider.ts
=> chore: remove version from ws proxy

examples/batch.ts, examples/identity_cr.ts, examples/indices.ts, examples/ink_e2e/main.ts, examples/multisig_transfer.ts, examples/polkadot_js_signer.ts, examples/transfer.ts, examples/transfer_sequence.ts, examples/xcm_asset_teleportation.ts, fluent/ExtrinsicStatusRune.ts, rune/ValueRune.ts
=> chore: get rid of `.log`, rename `.logStatus` to `.dbgStatus`

examples/entry_page.ts, fluent/StorageRune.ts
Resolves #643
Allows one to retrieve a list of entries as they do a list of keys.
```ts
import { Uniques } from "statemint/mod.ts"
const collections = Uniques.Class.entryPage(100)
const result = await collections.run()
console.log(result)
```
Will soon be complemented by #567.
> Note: was confused by the name of the result, storage changeset. Doesn't represent a diff after all.
=> feat: entry page retrieval

import_map.json, patterns/identity.ts
Deno version 1.31.0 was just released. Running examples now results in an error (says that mapping from `http://localhost:4646/` to `./` is illegal). For now, we'll do away with the mapping.
=> fix: new version of deno throws error relating to import map

.github/workflows/star.yml, .github/workflows/test.yml, _tasks/star.ts, main.ts, providers/frame/dev.ts, providers/frame/zombienet.ts
Based on trial and error, it seems that sometimes `zombienet` Deno resources are not properly released.
I haven't been able to identify the root cause.
The `unload` event is not fired in these cases.
```
self.addEventListener("unload", () => Deno.exit(status.code))
```
This PR 
- closes child processes started with `Deno.run`
- closes child processes `piped` file descriptors
- upgrades polkadot, polkadot-parachain and zombienet versions
Note: I've observed that the `star` task sometimes keeps running even after closing fd and processes 
Another theory to explore is that this could be correlated to a recent Deno version upgrade.
This is related to https://github.com/paritytech/capi/pull/625
=> fix: process resource cleanup in start task

codegen/frame/codecs.ts, frame_metadata/Metadata.ts, providers/frame/dev.ts, scale_info/Codec.ts, scale_info/Ty.ts
Replaces no-longer-valid usage of `scale-ts` `stringUnion` with `literalUnion`.
=> fix: usage of new `scale-ts` version

_tasks/dnt.ts, examples/size_tree.ts, fluent/StorageRune.ts, patterns/sizeTree.ts
A pattern for resolving a pallet-indexed lookup of storage-entry-size lookups.
```ts
import { sizeTree } from "capi/patterns/sizeTree.ts"
import { chain } from "polkadot_dev/mod.ts"
const result = await sizeTree(chain).run()
```
In this example `result` evaluates to something along the following lines:
```ts
{
System: {
Account: 1040,
ExtrinsicCount: undefined,
BlockWeight: 11,
AllExtrinsicsLen: undefined,
BlockHash: 32,
ExtrinsicData: undefined,
Number: undefined,
ParentHash: 32,
Digest: undefined,
Events: undefined,
EventCount: undefined,
EventTopics: undefined,
LastRuntimeUpgrade: 11,
UpgradedToU32RefCount: 1,
UpgradedToTripleRefCount: 1,
ExecutionPhase: undefined
},
// other pallets...
}
```
Will hold off on merging until #655, so that we can ensure this pattern is accessible to …
=> feat: `storageRune.size` method + `sizeTree` pattern

rpc/Connection.ts, rpc/smoldot.test.ts
- Fixes subscription handler setup (`Connection.handle` was invoked before the subscription handler was set)
- Add unit test for Smoldot
=> fix: smoldot connection race condition

deps/std/encoding/base64.ts, examples/multisig_transfer.ts, examples/virtual_multisig.ts, patterns/multisig/MultisigRune.ts, patterns/multisig/VirtualMultisigRune.ts, patterns/multisig/mod.ts, patterns/proxy/events.ts, patterns/proxy/mod.ts, patterns/proxy/replaceDelegateCalls.ts, words.txt
Closes #658
Closes #555
This PR takes the learnings from #555 and integrates them into a `VirtualMultisigRune`. One can deploy a `VirtualMultisigRune` like so:
```ts
import { alice, bob, charlie, hex } from "capi"
import { VirtualMultisig } from "capi/patterns/multisig/mod.ts"
import { chain } from "polkadot_dev/mod.ts"
const state = await VirtualMultisigRune
.deployment(chain, {
founders: [alice.publicKey, bob.publicKey, charlie.publicKey],
threshold: 2,
deployer: alice,
})
.hex
.run()
await Deno.writeTextFile("persist_this.txt", state)
```
To hydrate from the state hex, we do the following.
```ts
const vMultisig = VirtualMultisigRune.hydrate(chain, state)
```
To ratify a call from the stash account (signatory -> signatory proxy -> multisig -> stash), we can use virtual multisig's ratify …
=> feat: virtual multisigs

.github/workflows/release.yml
=> ci: add necessary bin setups to release workflow

util/mod.ts
=> fix: add tsFormatter to moderate excludes

.github/PULL_REQUEST_TEMPLATE.md
As pointed out by @tjjfvi,––at this point in development––we likely don't need an issue for every PR (especially when they're simple one-off tasks). this can create a fair amount of noise. Most contributors will know that it's good educate to discuss large code changes before making them.
=> docs: remove PR template

_tasks/star.ts, examples/ink_e2e/main.ts, examples/xcm_asset_teleportation.ts
Revert a bad copy/paste from #666 and add extra logs for error debugging
=> fix: star task

fluent/ExtrinsicStatusRune.ts
```diff
const result = await Balances
.transfer({
value: 12345n,
dest: bob.address,
})
.signed({ sender: alice })
.sent()
+ .finalizedHash()
.run()
```
`inBlockHash` as well
=> feat: block hash methods

Readme.md
Use local server, not capi.dev, which needs some work before we can recommend it as a usage path.
=> docs: fix readme example instruction

_tasks/dnt.ts, deps/scale.ts
Updating scale usually needs more than just bumping the version, and we're typically on top of scale updates anyway.
=> chore: update scale; exclude scale from udd

crypto/ss58.test.ts, crypto/ss58.ts, patterns/signature/polkadot.ts
Resolves #619 
Add ss58 encoding and decoding for different payload and checksum lengths (see [ss58-format](https://docs.substrate.io/reference/address-formats/)).
Note: `MultiAdress.Index` use formats whose checksum length is `1` provided that the index is of type `u8`, `u16`, `u32` or `u64` (`1`, `2`, `4` or `8` byte payload).
=> feat: improve ss58 encoding/decoding

_tasks/dnt.ts, codegen/FrameCodegen.ts, codegen/TypeCodegen.ts, deps/capi_crypto_wrappers.ts, deps/smoldot.ts, deps/smoldot/client.d.ts, deps/std/archive.ts, main.ts, providers/frame/FrameProvider.ts, providers/frame/FrameProxyProvider.ts, providers/frame/common.ts, rpc/smoldot.test.ts, rpc/smoldot.ts, rune/ValueRune.ts, util/notifier.ts
Resolves #719
```jsonc
// package.json
{
"type": "module",
"dependencies": {
"@capi/westend-dev": "http://localhost:4646/frame/dev/westend/@latest/pkg.tar",
"capi": "file:../capi/target/npm/capi-v0.1.0.tgz"
}
}
```
```ts
// transfer.ts
import { alice, bob } from "capi";
import { Balances } from "@capi/westend-dev";
import { signature } from "capi/patterns/signature/polkadot";
const result = await Balances
.transfer({
value: 12345n,
dest: bob.address,
})
.signed(signature({ sender: alice }))
.sent()
.dbgStatus()
.finalizedEvents()
.run();
console.log(result);
//          ^? - const result: Event<EventsChain<EventsChain<WestendDev>>>[]
```
```ts
// npx ts-node-esm transfer.ts
ready
{
inBlock: '0x54fe90dc4c91d1770ecfec14b632a3d41d0348921cbcd058d2d271008e1952fa'
}
{
finalized: …
```
=> feat: node support in codegen server

main.ts, server/capi.dev/delegatee.ts, server/capi.dev/delegator.ts, server/factories.ts, server/handler.ts, server/mod.ts, util/cache/base.ts, util/cache/fs.ts, util/cache/memory.ts, util/cache/s3.ts
Resolves #720
https://capi.dev/@pr:764/frame/wss/rpc.polkadot.io/@latest/mod.js
=> feat: capi.dev

fluent/StorageRune.ts, rpc/ws.ts
Fixes storage entry and key page retrieval
=> fix: entry page and key page usage

main.ts, providers/frame/FrameBinProvider.ts, providers/frame/common.ts, providers/frame/contracts_dev.ts, providers/frame/polkadot_dev.ts
=> fix: run bin abort signal

_tasks/dnt.ts
Fixes https://github.com/paritytech/capi/issues/778
Works for both Node.js environment and the browser
`isomorphic-ws` lib uses:
- [ws](https://github.com/websockets/ws) on Node
- [global.WebSocket](https://developer.mozilla.org/en-US/docs/Web/API/WebSocket) in browsers
=> fix: shim isomorphic-ws for WebSocket

rune/ValueRune.ts
#790 
possible changes: 
- change name of `RunMatch` (RunHandle is already taken, maybe refactor)
- handleError function
=> feat: handle rune

crypto/test_pairs.ts, examples/balance.ts, examples/batch.ts, examples/fee_estimate.ts, examples/identity_cr.ts, examples/indices.ts, examples/multisig_pure_proxy_stash.ts, examples/multisig_transfer.ts, examples/polkadot_js_signer.ts, examples/transfer.ts, examples/transfer_sequence.ts, examples/virtual_multisig.ts, providers/frame/common.ts, words.txt
Fixes #760
Enables one to use `createUsers` (renamed from `users`) without specifying a count, which will cause it to default to a record (not a list) of 26 named `Sr25519`s.
```ts
const { alexa, billy, carol, david } = await createUsers()
```
Count specificity still works as is did before.
```ts
const [a, b, c, d] = await createUsers(4)
```
=> chore: improve users util

patterns/multisig/MultisigRune.ts
resolves: #827
https://github.com/paritytech/substrate/pull/13268
broke the weight calculation causing the proof size requirement to exceed 0 
need to wait for this to be merged and released is my understanding
https://github.com/paritytech/substrate/pull/13766
=> fix: multisig rune proof size

examples/.ignore, examples/multisig/virtual.eg.ts, examples/paginate.eg.ts, examples/read/now.eg.ts, examples/sign/ed25519.eg.ts, examples/tx/handle_errors.eg.ts, examples/watch.eg.ts
=> fix: misc examples broken

examples/sign/offline.ts, fluent/SignedExtrinsicRune.ts, words.txt
A follow-up to #756
Simplifies taking a signed extrinsic hex and turning it into a `SignedExtrinsicRune` (ostensibly for submission).
```ts
// Create and sign the extrinsic. Extract the hex.
const hex = await Balances
.transfer({
value: 12345n,
dest: billy.address,
})
.signed(signature({ sender: alexa }))
.hex()
.run()
// Save `hex` however you'd like (potentially sending to a relayer service,
// writing to disk, etc.).
save(hex)
// Hydrate the signed extrinsic, submit it and await finalization.
await SignedExtrinsicRune
.fromHex(chain, hex)
.sent()
.dbgStatus("Tx status:")
.finalized()
.run()
```
=> feat: add `SignedExtrinsicRune` `from` and `fromHex` methods

devnets/syncConfig.ts, import_map.json
Before, was incorrect / reflected the relay chain name.
```diff
- import { RococoDev } from "@capi/rococo-dev/statemine"
+ import { Statemine } from "@capi/rococo-dev/statemine"
```
=> fix: generated para name

.trunignore, examples/smoldot.eg.ts, fluent/ChainRune.ts, fluent/StorageRune.ts, rpc/smoldot.ts
Fixes #865
Closes #871
- enable one to override a codegened `ChainRune` with a smoldot connection using the `with` method
- reference counting chain count for graceful smoldot exit
- use `hex.encodePrefixed` instead of `hex.encode` (otherwise, smoldot storage retrievals throw)
=> fix: misc. smoldot cleanup

.github/workflows/checks.yml, devnets/chainSpec.ts, devnets/startNetwork.ts
resolves #872 
Add support for additional validators.
This change will add support up to 6 parachains.
How to test?
```ts
import { binary, createTempDir, startNetwork } from "./devnets/mod.ts"
const controller = new AbortController()
Deno.addSignalListener("SIGINT", () => controller.abort())
Deno.addSignalListener("SIGTERM", () => controller.abort())
const polkadot = binary("polkadot", "v0.9.38")
const polkadotParachain = binary("polkadot-parachain", "v0.9.380")
const network = await startNetwork(
await createTempDir(),
{
binary: polkadot,
chain: "rococo-local",
parachains: {
statemine: {
id: 1000,
binary: polkadotParachain,
chain: "statemine-local",
},
westmint: {
id: 2000,
binary: polkadotParachain,
chain: "westmint-local",
},
contracts: {
id: 3000,
binary: polkadotParachain,
chain: …
```
=> feat: configure devnet validators

codegen/TypeCodegen.ts
Used `Rune.object` without the leading `C.` in codegen.
Not sure why #893's CI didn't fail
**EDIT**:
Didn't error bc the XCM example (the only example which currently makes use of the factories) is ignored. Given that this is a runtime error and it's never run, slipped by CI.
=> fix: typegen typo

examples/multisig/virtual.eg.ts
its always printed after the `if` statement so no need to print it twice.
=> chore: delete duplicate vmultisig state console log

examples/multisig/basic.eg.ts, examples/multisig/stash.eg.ts, patterns/multisig/MultisigRune.ts, patterns/multisig/VirtualMultisigRune.ts
- add `nonExecuting` to `MultisigRune.ratify`
- remove `MultisigRune.approve`
=> feat: improve MultisigRune.ratify

.github/workflows/checks.yml
https://github.com/denoland/deno/pull/18705 was released in [v1.32.5](https://github.com/denoland/deno/releases/tag/v1.32.5)
Resolves #892
=> ci: unpin deno in examples job

deps/ed25519.ts, deps/npm/noble/ed25519.ts, devnets/startNetwork.ts, examples/sign/ed25519.eg.ts, words.txt
Resolves https://github.com/paritytech/capi/issues/869
Libp2p encodes keys in a [protobuf](https://github.com/libp2p/go-libp2p/blob/master/core/crypto/pb/crypto.proto) containing a key *type* and the encoded key (where the encoding depends on the type).
Peer IDs are derived by hashing the encoded public key with [multihash](https://github.com/multiformats/multihash). Keys that serialize to more than 42 bytes must be hashed using sha256 multihash, keys that serialize to at most 42 bytes must be hashed using the "identity" multihash codec. See [docs](https://github.com/libp2p/specs/blob/master/peer-ids/peer-ids.md#keys).
Therefore, the `peerId` is derived as follows
```
peerId = multihash(protobuf.encode(ed25519PublicKey))
```
The first 6 bytes of `[0, 36, 8, 1, 18, 32, ...publicKey]` are …
=> feat: update libp2p peerId derivation

.vscode/settings.json, Readme.md
=> docs: update readme to reflect new config DX

_tasks/dnt.ts
Every non-node-shim, non-test ts file is now an entry specified in exports.
=> chore: generate pattern entries

import_map.json, nets.ts
Companion PR https://github.com/paritytech/capi-binary-builds/pull/36
Use the `polkadot` and `polkadot-parachain` patched version with 2s and 4s block times.
FYI, I did see an improvement in individual example runs but I did not see an improvement in the `deno task test:eg` timings.
=> feat: use polkadot/polkadot-parachain patched

examples/multisig/virtual.eg.ts, patterns/multisig/VirtualMultisigRune.ts
Allows you to specify an existing stash for a virtual multisig. This feature was requested by capi multisig app team.
Tested with `deno task run examples/multisig/virtual.eg.ts --use-stash`
=> feat: optional stash for virtual multisig

_tasks/dnt.ts, cli/sync.ts, mod.ts
Fix `dnt` shims by excluding
- files from `target|_tasks|examples`
- `deps/shims/ws.ts` and `deps/shims/shim-deno.ts` from the entry points
This PR also fixes `capi sync --package-json package.json` which is needed for https://github.com/paritytech/capi-vite-example/pull/1
=> fix: dnt shims

fluent/CodecRune.ts, patterns/multisig/MultisigRune.ts, patterns/multisig/VirtualMultisigRune.ts
Fixes #733.
Basic copy and paste implementation from `VirtualMultisigRune` except parameters changed.
=> feat: add fromHex to MultisigRune

nets/DevNetSpec.ts
Regression likely introduced around the time of #983
=> fix: path as bin in dev net spec props

Readme.md, examples/dynamic.eg.ts, examples/paginate.eg.ts, fluent/StorageRune.ts, patterns/multisig/MultisigRune.ts
"Limit" more accurately describes the prop.
=> chore: rename page-retrieval `count` to `limit`

_tasks/dnt.ts
This `dnt` shim is no longer necessary since both modern browsers and Node (since `v20`) have the `crypto` global.
See https://nodejs.org/api/globals.html#crypto_1
=> feat: remove dnt crypto shim

patterns/multisig/MultisigRune.ts
Changes type of `depositor` from `bigint` to `Uint8Array` as it's an `AccountId`.
I think this is the wrong type here in capi. It's supposed to be an `AccountId` so it should also be a Uint8Array, like everywhere else.
https://github.com/paritytech/substrate/blob/master/frame/multisig/src/lib.rs#LL107C1-L119C2
=> fix: MultisigRune - `depositor` as `Uint8Array`

util/normalize.ts
Resolves #1033 
Note:
I noticed that sometimes a request to `http://localhost:4646/hash/some-chain/types.d.ts` runs out of memory when `shiki` is doing the code rendering
```
<--- Last few GCs --->
[13812:0x140018000]   419196 ms: Mark-Compact 1398.0 (1425.3) -> 1396.8 (1425.3) MB, 310.00 / 0.00 ms  (average mu = 0.095, current mu = 0.001) allocation failure; scavenge might not succeed
[13812:0x140018000]   419508 ms: Mark-Compact 1397.8 (1425.3) -> 1396.8 (1425.3) MB, 312.58 / 0.00 ms  (average mu = 0.050, current mu = 0.001) allocation failure; scavenge might not succeed
<--- JS stacktrace --->
#
#
=> fix: codegen ts keyword

fluent/ExtrinsicRune.ts
```ts
const callHex = await westendDev.Balances
.transfer({
value: 12345n,
dest: billy.address,
})
.hex
.run()
const x = ExtrinsicRune.fromHex(westendDev, hex)
```
=> feat: static `from` methods on `ExtrinsicRune`

_tasks/dnt.ts, deps/smoldot.ts
After migrating from https://github.com/paritytech/smoldot to https://github.com/smol-dot/smoldot, the package name has changed from `smoldot` to `smoldot2`.
This PR removes the deprecated package and replaces it with the new version.
=> chore(deps): use smoldot 1.0

fluent/ExtrinsicRune.ts, frame_metadata/Extrinsic.ts, patterns/compat/pjs_sender.ts
Fixes #1041
```ts
import { is, SignerError } from "capi"
await polkadotDev.Balances
.transfer({
value: 12345n,
dest: billy.address,
})
.signed(signature({ sender: sender(alexaSs58) }))
.sent()
.dbgStatus("Transfer:")
.finalized()
.handle(is(SignerError), (error) => error.access("inner").dbg("Likely a cancellation!"))
.run()
```
=> feat: enable handling of signer error within rune system

_tasks/dnt.ts, cli/init.ts, cli/sync.ts, deps/std/jsonc.ts, main.ts
Resolves #940
In a Deno project, simply do the following.
```sh
deno run -A https://deno.land/x/capi/main.ts init
```
Or in a Node project
```sh
npm i capi
npx capi init
npm run capi:sync
```
**How to test this locally with Node?**
```sh
deno task dnt
cd target/npm
npm pack
npm i /path/to/target/npm/capi-v0.0.0-local.tgz
npx capi init
npm run capi:sync
```
Then, validate that
- `nets.ts` has been created
- `@capi/polkadot` and `@capi/polkadot-dev` have been added to `package.json` dependencies
- `capi:sync` and `capi:serve` npm scripts have been added
=> feat: CLI `init` command

_tasks/generate_artifacts.ts, cli/init.ts, mod.ts, nets.ts, nets/chain_spec/addDevUsers.ts, server/client/createDevUsers.ts
Closes https://github.com/paritytech/capi/issues/1053 https://github.com/paritytech/capi/issues/1038
This PR improves 
- the bundle size for web
- `webpack` configuration because `externals["node:*"]` is no longer required
- `vite` configuration because `build.rollupOptions.shimMissingExports` is no longer required  
Webpack Bundle Analyzer before and after this change
`vite-bundle-visualizer` after this change
=> feat: improve bundle size

.devcontainer/Dockerfile
Capi only works with node 20+ so dev container should be set to node 20.
=> chore: update dev container node version

_tasks/dnt.ts
I think it makes sense for a file to take precedence over a same-named dir's `mod.ts`, hence, let's just exclude the `nets.ts` from being matched by the fs walker.
=> fix: make npm pkg nets importable

.github/workflows/checks.yml, _tasks/dnt.ts, cli/sync.ts, deps/dnt.ts, deps/shims/loader.node.ts, deps/shims/ts-node-esm.ts, server/detectVersion.node.ts
- Creates a `capi/loader` that just points to `ts-node/esm` so that users don't need to install `ts-node` themselves
- Fixes the sync command to default the server to a correctly versioned capi.dev url (before it defaulted to the unversioned `https://capi.dev/`)
=> feat: improve node cli experience

examples/ink/interact.eg.ts, fluent/ConnectionRune.ts, rune/MetaRune.ts, rune/Rune.ts, rune/ValueRune.ts
=> fix: flatten cleanup

examples/read/fellowship_identities.eg.ts, import_map.json, nets.ts, words.txt
An example that makes use of Polkadot and the Collectives parachain.
=> chore: fellowship identities derived read example

patterns/compat/pjs_sender.ts
=> fix: add `ChargeAssetTxPayment` to `pjs_sender`

.github/workflows/checks.yml, _tasks/dnt.ts, deps/shims/register-ts-node.node.ts
CJS compat broke all of the patterns (as the codegen is ESM); moving back to ESM-only.
Also resolves #1096
=> fix: node support

_tasks/dnt.ts, codegen/CodecCodegen.ts, codegen/TypeCodegen.ts, deps/scale.ts, scale_info/transformTys.ts, server/factories.ts, util/normalize.ts
Depends on https://github.com/paritytech/scale-ts/pull/166
This uses the new `$.documented` api to attach docs to the metadata codecs, which makes it much easier to consume in the codegen.
Note that this does not add doc comments to the frame codegen. See issue #1141.
Resolves #723
Resolves #920
=> feat: add docs to metadata & codegen types

Readme.md
Deletes the build tool integration doucmentation because it can be found at https://github.com/paritytech/docs.capi.dev/blob/main/docs/setup/build_tool_integration.md
=> docs: remove build tool integration documentation

patterns/compat/pjs_sender.ts
A follow up to https://github.com/paritytech/capi/pull/1105
unfortunately the nft collection creation still wasn't working on gamma 1 of capi
code was breaking on assetId field, which is part of ChargeAssetTxPayment
this fixes the problem, though I'm not sure if a similar handler should also be added to
https://github.com/paritytech/capi/blob/main/patterns/compat/pjs_sender.ts#L62
and
https://github.com/paritytech/capi/blob/main/patterns/compat/pjs_sender.ts#L75
=> fix: add optional field handling to pjs compat

Readme.md, words.txt
#1163
Omitted "and below", since if we go below node version 14 this api doesn't exist.
=> fix: node compatibility docs
