paritytech/capi

deno.jsonc, effect/std/atoms/entryKey.ts, effect/std/entry.ts, effect/std/mapEntry.ts, effect/std/read.ts, frame_metadata/Codec.test.ts, frame_metadata/Key.test.ts, frame_metadata/Key.ts, frame_metadata/Metadata.ts, frame_metadata/test-util.ts
Good resource: https://www.shawntabrizi.com/substrate/transparent-keys-in-substrate/
=> feat: rework key encoding and implement key decoding

.github/workflows/fmt.yml, .github/workflows/test.yml, effect/std/atoms/codec.ts, effect/std/atoms/decoded.ts, effect/std/atoms/deriveCodec.ts, effect/std/atoms/entryMetadata.ts, effect/std/atoms/metadataDecoded.ts, effect/std/atoms/metadataLookup.ts, effect/std/atoms/palletMetadata.ts, effect/std/metadata.ts, effect/std/pallet.ts, effect/std/rpcCall.ts, util/types.ts
=> chore: check formatting on ci

.github/workflows/spellcheck.yml, words.txt
=> chore: CSpell GH workflow

Config.ts, examples/block.ts, examples/metadata.ts, known/methods.ts, rpc/Base.ts, rpc/common.ts, rpc/messages.ts, rpc/mod.ts, rpc/providers/proxy.ts, rpc/providers/smoldot.ts, rpc/providers/std.ts, runtime/watch.ts, util/types.ts
=> chore: declare rpc methods in non-method form

deno.jsonc, effect/atoms/Metadata.ts, effect/examples/balance.ts, effect/examples/first_ten_keys.ts, effect/examples/metadata.ts, effect/sys/Atom.type-test.ts, effect/sys/Run.ts, fluent/Signed.ts, rpc/messages.ts, rpc/providers/proxy.test.ts, rpc/providers/proxy.ts, rpc/providers/smoldot.ts, runtime/send.ts, test-util/Address.ts, test-util/ctx.ts, test-util/node.ts
- Get rid of certain lints, fix corresponding errors
- Fix resource usage error in local node util
=> chore: tweak lint config, fix lint errors, fix local node resource error

_tasks/dnt.ts, config/mod.ts, deps/scale.ts, effect/atoms/RpcCall.ts, effect/mod.ts
Fixes ensure builds usable in NextJS env.
=> chore:  DNT usage fixes

_tasks/dnt.ts, util/async.ts
Fix error in which we were attempting to copy (now-deleted) sr25519 wasm bindings
=> chore: fix DNT step fs copy error

deno.jsonc, effect/atoms/$ExtrinsicEncodeAsync.ts, effect/atoms/mod.ts, effect/std/submitAndWatchExtrinsic.ts, frame_metadata/Extrinsic.ts
Allows sign fns to produce either a signature or a promise resolving to a signature
=> feat: async encoding

Cargo.toml, _tasks/build_wasm.ts, _tasks/dnt.ts, config/mod.ts, effect/atoms/RpcCall.ts, effect/atoms/RpcSubscription.ts, effect/atoms/common.ts, effect/examples/transfer.ts, effect/std/submitAndWatchExtrinsic.ts, frame_metadata/Extrinsic.ts, hashers/mod.generated.js, known/configs.ts, known/types/author.ts, mod.ts, ss58/mod.generated.js, test-util/config.ts, util/iter.ts, util/watch.ts, wasm.rs, words.txt
- Fix incorrect westend ss58 prefix
- Fix wasm-loading issue for NextJS dev servers
- Clean up RPC effect errors
- Clean up `TransactionStatus` type
- Another pass at iter util
=> chore: misc tweaks

deno.jsonc, deps/dprint.ts, frame_metadata/Codec.ts, frame_metadata/Era.ts, frame_metadata/TyVisitor.ts, mod.ts, typegen/typegen.ts, words.txt
=> feat: typegen

.github/ISSUE_TEMPLATE/BUG_REPORT.md, .github/ISSUE_TEMPLATE/FEATURE_REQUEST.md, .github/PULL_REQUEST_TEMPLATE.md, .github/workflows/test.yml, CODE_OF_CONDUCT.md, CONTRIBUTING.md, Readme.md, deno.jsonc
Related #43 
Add the following files to configure GH presence
- `CONTRIBUTING.md`
- `CODE_OF_CONDUCT.md`
- `.github/ISSUE_TEMPLATE/FEATURE_REQUEST.md`
- `.github/ISSUE_TEMPLATE/BUG_REPORT.md`
- `.github/PULL_REQUEST_TEMPLATE.md`
=> chore: GH Presence

.github/workflows/profanitycheck.yml, words.txt
Resolves #39 
In order to [check for bad words](https://github.com/paritytech/capi/issues/39), I checked out some existing solutions which we could integrate in our repo:
- Github Action [mind-your-language-action](https://github.com/tailaiw/mind-your-language-action)
- Github Action [restrict-cursing-action](https://github.com/sobolevn/restrict-cursing-action)
- Python library [profanity-filter](https://github.com/rominf/profanity-filter)
- Python library [profanity-check](https://github.com/vzhou842/profanity-check)
- Google [profanity word list](https://github.com/coffee-and-fun/google-profanity-words)
Considering the number of stars, frequency of update and ease of integration, I have integrated mind-your-language-action for now. However, we can discuss more and I can update the PR …
=> Profanity check action

rpc/providers/proxy.ts, rpc/providers/ws_container.test.ts, rpc/providers/ws_container.ts
=> feat: add RPC client fallback URLs

_tasks/dnt.ts, deps/scale.ts, effect/std/watchBlocks.ts, examples/watch_blocks.ts, frame_metadata/Codec.ts
Updates scale to fix an issue with extrinsic decoding
New example: `deno task run examples/watch_blocks.ts`
=> Fix watch blocks

.github/ISSUE_TEMPLATE/BUG_REPORT.md, .github/ISSUE_TEMPLATE/FEATURE_REQUEST.md, .github/PULL_REQUEST_TEMPLATE.md
Misc. template cleanup
- Leave titles blank
- Fewer / simpler instructions
- PR template has checkboxes
=> chore: template cleanup

codegen/utils.ts
This change was supposed to be in #229 but I failed to save 😅
=> fix: missing codegen change

.github/workflows/check_secrets.yml, .github/workflows/configure.yml, .github/workflows/mind_your_language.yml, .github/workflows/validate_pr_title.yml, words.txt
- PR format validation
- fix trigger events for trufflehog and mind your lang workflows
- tiny tweaks
=> ci: misc cleanup

.github/PULL_REQUEST_TEMPLATE.md
We have a GH check for this now
=> chore: remove PR title format checkbox

codegen/codecVisitor.ts, codegen/genMetadata.ts, codegen/typeVisitor.ts, frame_metadata/Codec.ts, frame_metadata/Extrinsic.ts, frame_metadata/TyVisitor.ts, mod.ts, util/$lenPrefixed.ts, util/mod.ts
This fixes the issue @kratico was running into with the multisig transfer
=> feat: add `lenPrefixedWrapper` to support `WrapperOpaque` and `WrapperKeepOpaque` types

.github/workflows/udd.yml
Should hopefully fix the failing "basic tests" thing
=> chore: update update deno dependencies workflow

_tasks/dnt.ts
=> chore: add `webSocket` dnt shim

codegen/server/prod.ts
=> chore: test branch

codegen/server/capi_repo.ts, codegen/server/deploy.ts, codegen/server/git_utils.ts, codegen/server/local.ts, codegen/server/server.ts
Should hopefully fix https://capi.dev/@v0.1.0-beta.18/ (once we release)
=> fix: tag version on codegen server

Readme.md
A link was broken probably during some refactoring.
=> docs: fix broken link

effects/extrinsic.ts, examples/multisig_transfer.ts
=> chore: map names in fee estimate effect

.github/ISSUE_TEMPLATE/BUG_REPORT.md
Resolves #466 
Removes unnecessary asterisks.
=> chore: fix asterisks in bug report template

effects/entryRead.ts
Use entryReadRaw in entryRead
Note: I thought that there was a caching issue but it may have been a local environment issue.
=> feat: use entryReadRaw in entryRead

.devcontainer/devcontainer.json
=> chore: add better toml to dev container

.github/workflows/dev-container.yml, .github/workflows/test.yml
=> feat: add timeouts to gh workflow tests

examples/smart_contract.ts, examples/xcm_teleport_assets.ts, import_map.json
Fixing a typo + issues with rewrite suggestions in vscode
=> chore: import cleanup

.github/workflows/dev-container.yml, Dockerfile
=> fix: dev container gh workflow

.github/CODEOWNERS
(per discussion with @harrysolovay)
=> chore: tjjfvi's greedy power grab

.github/workflows/dev-container.yml, .github/workflows/fmt.yml, .github/workflows/lint.yml, .github/workflows/spellcheck.yml, .github/workflows/star.yml, .github/workflows/test.yml
=> ci: add merge_group workflow trigger

providers/frame/dev.ts, server/PathInfo.test.ts, server/PathInfo.ts
=> feat: support empty target

deps/case.ts, examples/transfer_sequence.ts, rune/Rune.ts
An example that showcases sequential txs
=> chore: transfer sequence example

.github/actions/setup-binary/action.yml, .github/workflows/test.yml, Dockerfile
=> chore: update zombienet for test gh workflow

util/mod.ts
=> fix: actually fix util/mod.ts

_tasks/dnt.ts
=> fix: crypto wasm size

crypto/hashers.test.ts, crypto/hashers.ts, frame_metadata/Metadata.ts
Fixes https://github.com/paritytech/capi/issues/714
=> feat: add Blake2_512 hasher

.devcontainer/devcontainer.json, .vscode/settings.json
=> chore: update dev container syntax

patterns/multisig/VirtualMultisigRune.ts
#712
Filtering messed up the ordering, this fixes it.
=> fix: virtual multisig ownership swap events ordering

examples/batch.ts, examples/identity_cr.ts, examples/indices.ts, examples/multisig_pure_proxy_stash.ts, examples/multisig_transfer.ts, examples/polkadot_js_signer.ts, examples/transfer.ts, examples/transfer_sequence.ts, examples/virtual_multisig.ts, examples/xcm_asset_teleportation.ts, fluent/ExtrinsicRune.ts, import_map.json, patterns/multisig/VirtualMultisigRune.ts, patterns/signature/polkadot.ts
```diff
const result = await Balances
.transfer({
value: 12345n,
dest: bob.address,
})
- .signed(chain, signature({ sender: alice }))
+ .signed(signature({ sender: alice }))
.sent()
.dbgStatus()
.finalizedEvents()
.run()
```
=> refactor: adjust signature pattern usage

LICENSE
Did you know today is the Entish New Year?
=> chore: 2023

providers/frame/common.ts, server/capi.dev/delegator.ts, server/handler.ts
=> fix: cors server errors

.github/workflows/checks.yml, devnets/createTempDir.ts
Archive devnet `stdout`/`stderr` if the workflow fails
=> feat: archive devnet stdout/stderr on workflow failure

.github/workflows/checks.yml
I'm tossing my hat in the ring
=> ci: downgrade deno to fix examples

codegen/TypeCodegen.ts, examples/sign/ed25519.eg.ts, examples/xcm/asset_teleportation.eg.ts, fluent/ExtrinsicRune.ts
Resolves #874
Does the same for named tuples and arrays as well
=> feat: codegened object and tuple factories

_tasks/dnt.ts, deps/shims/Deno.node.ts, deps/shims/command.node.ts, deps/shims/register.node.ts, deps/shims/shim-deno.ts
Should fix capi in the browser.
=> fix: lazy shims

examples/multisig/basic.eg.ts, examples/multisig/stash.eg.ts, examples/multisig/virtual.eg.ts, patterns/multisig/MultisigRune.ts
Adds fund method to multisig rune
=> feat: add fund to multisig rune

patterns/multisig/VirtualMultisigRune.ts
=> fix: add unhandle failed to proxy creation calls

rune/Rune.ts, rune/_empty.d.ts
=> fix: dnt any types

rpc/Connection.ts, rune/Rune.ts, rune/_empty.d.ts
=> fix: parallel rpc connection

fluent/ChainRune.ts, fluent/StorageRune.ts
=> fix: default to finalized block hash

codegen/TypeCodegen.ts, codegen/frameCodegen.ts
=> fix: literal union runtime codegen

_tasks/dnt.ts
Resolves #1007
(I could've sworn this was working...)
=> fix: dnt any

rune/Rune.ts, rune/ValueRune.ts
=> feat: rune traces

_tasks/dnt.ts, deps/capi_binary_builds.ts
Closes #1017 
Depends on https://github.com/paritytech/capi-binary-builds/pull/62
=> fix: node capi sync

_tasks/dnt.ts, deps/wat_the_crypto.ts
Related to https://github.com/paritytech/capi/issues/990
=> chore: upgrade wat_the_crypto

nets/DevNetSpec.ts
Resolves https://github.com/paritytech/capi/issues/928
=> feat: add support for updated substrate cli args

patterns/multisig/MultisigRune.ts
```ts
const ss58Addr = await multisig.ss58.run()
```
=> feat: convenience prop for ss58 access on `MultisigRune`

_tasks/dnt.ts, _tasks/generate_artifacts.ts, crypto/Sr25519.ts, deps/capi_crypto_wrappers.ts, deps/wat_the_crypto.ts, nets/chain_spec/addDevUsers.ts, words.txt
https://github.com/paritytech/wat-the-crypto/pull/14
=> feat: wat the sr25519

examples/dev/metadata.eg.ts, rune/Rune.ts, rune/Trace.test.ts, rune/Trace.ts
=> feat: rework trace

deps/shims/Deno.node.ts, rune/Trace.ts
Resolves #1067
Tested off of #1031 and it does indeed work
=> fix: trace

examples/smoldot/fetch_chainspec.eg.ts, examples/smoldot/smoldot.eg.ts
Will help us avoid crossing the deno.land/x size limit
=> fix: get rid of chainspec artifact in smoldot example

deps/shims/Deno.node.ts
For hopefully the last time...
=> fix: trace (round 2)

examples/dynamic.eg.ts, import_map.json
=> chore: resync

rune/Rune.test.ts, rune/ValueRune.ts, rune/is.ts
=> feat: add match

Readme.md
=> docs: update readme

rune/Rune.ts
Fixes #1147
Fixes #1159
Thanks @josepot for catching these issues!
=> fix: two rune bugs

fluent/StorageRune.ts
=> fix: return empty list when no entries

examples/multisig/hydrate.eg.ts
=> chore: multisig serialize and hydrate example

Readme.md
Will hopefully spare some developers of unresolved nets types.
=> docs: add note about tsconfig requirements
